apiVersion: v1
kind: Service
metadata:
  name: moderation-serv 
spec:
  type: NodePort
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 8003
      targetPort: 8003
  
